spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/msaquiba/suzki.git"
          refresh-rate: 60

  security:
    user:
      name: saquib
      password: system



